### ISSUE TITLE
Request: Extracting AES key process

### ISSUE THREAD

**Issue by johnc2k** [suborb/huafan-wifiswitch#1]
Hi,

Would you mind listing the steps involved in extracting the AES & IVS keys?
I have a HF-W02 which appears almost identical but does not respond to commands (so I am assuming the encryption keys are different). I have confirmed I am using the default password of "888888".
My plug does respond back to the "Discover" command.

Thanks

John

**Comment by suborb** [comment]
I think the keys are the same, the commands are different. These switches don't respond if they don't understand the command.

Try AT+OPEN and AT+CLOSE - i.e. the same commands without the 'S' after the +.

**Comment by johnc2k** [comment]
Your absolutely right, thanks for the fast reponse

**Comment by suborb** [comment]
No worries, glad it worked - I've only come across the HF-W0B switches.

Can you confirm that the other commands work as expected (i.e. stripping off the S?)

**Comment by johnc2k** [comment]
Discover, On, Off, Version, GetSignal, works
GetCurrent, GetTime does not work
